syntax = "proto3";

package api.auth.v1;

option go_package = "github.com/mikhaeris/sky-bank/auth_service/api/auth/v1;authv1";

service OtpService {
  rpc CreateChallenge(CreateChallengeRequest) returns (CreateChallengeResponse);
  rpc VerifyChallenge(VerifyChallengeRequest) returns (VerifyChallengeResponse);
}

enum OtpChannel {
  OTP_CHANNEL_UNSPECIFIED = 0;
  OTP_CHANNEL_EMAIL = 1;
  OTP_CHANNEL_SMS = 2;
}

enum OtpPurpose {
  OTP_PURPOSE_UNSPECIFIED = 0;
  OTP_PURPOSE_EMAIL_VERIFICATION = 1;
}

message CreateChallengeRequest {
  string destination = 1;
  OtpChannel channel = 2;
  OtpPurpose purpose = 3;
}

message CreateChallengeResponse {
  string challenge_id = 1;
}

message VerifyChallengeRequest {
  string challenge_id = 1;
  string code = 2;
}

message VerifyChallengeResponse {
  bool verified = 1;
}
