syntax = "proto3";

package api.auth.v1;

import "buf/validate/validate.proto";

option go_package = "github.com/mikhaeris/sky-bank/auth_service/pkg/auth/v1;authv1";

service OtpService {
  rpc CreateChallenge(CreateChallengeRequest) returns (CreateChallengeResponse);
  rpc VerifyChallenge(VerifyChallengeRequest) returns (VerifyChallengeResponse);
}

enum OtpChannel {
  OTP_CHANNEL_UNSPECIFIED = 0;
  OTP_CHANNEL_EMAIL = 1;
  OTP_CHANNEL_SMS = 2;
}

enum OtpPurpose {
  OTP_PURPOSE_UNSPECIFIED = 0;
  OTP_PURPOSE_EMAIL_VERIFICATION = 1;
}

message CreateChallengeRequest {
  string destination = 1 [
    (buf.validate.field).string.min_len = 1
  ];
  OtpChannel channel = 2 [
    (buf.validate.field).enum = {defined_only: true, not_in: [0]}
  ];
  OtpPurpose purpose = 3 [
    (buf.validate.field).enum = {defined_only: true, not_in: [0]}
  ];
}

message CreateChallengeResponse {
  string challenge_id = 1;
}

message VerifyChallengeRequest {
  string challenge_id = 1 [
    (buf.validate.field).string.uuid = true
  ];
  string code = 2 [
    (buf.validate.field).string.pattern = "^[0-9]{6}$"
  ];
  string destination = 3 [
    (buf.validate.field).string.min_len = 1
  ];
  OtpPurpose purpose = 4 [
    (buf.validate.field).enum = {defined_only: true, not_in: [0]}
  ];
}

message VerifyChallengeResponse {
  bool verified = 1;
}
