// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: auth/v1/challenge.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OtpChannel int32

const (
	OtpChannel_OTP_CHANNEL_EMAIL OtpChannel = 0
	OtpChannel_OTP_CHANNEL_SMS   OtpChannel = 1
)

// Enum value maps for OtpChannel.
var (
	OtpChannel_name = map[int32]string{
		0: "OTP_CHANNEL_EMAIL",
		1: "OTP_CHANNEL_SMS",
	}
	OtpChannel_value = map[string]int32{
		"OTP_CHANNEL_EMAIL": 0,
		"OTP_CHANNEL_SMS":   1,
	}
)

func (x OtpChannel) Enum() *OtpChannel {
	p := new(OtpChannel)
	*p = x
	return p
}

func (x OtpChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OtpChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_challenge_proto_enumTypes[0].Descriptor()
}

func (OtpChannel) Type() protoreflect.EnumType {
	return &file_auth_v1_challenge_proto_enumTypes[0]
}

func (x OtpChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OtpChannel.Descriptor instead.
func (OtpChannel) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_challenge_proto_rawDescGZIP(), []int{0}
}

type OtpPurpose int32

const (
	OtpPurpose_OTP_PURPOSE_EMAIL_VERIFICATION OtpPurpose = 0
)

// Enum value maps for OtpPurpose.
var (
	OtpPurpose_name = map[int32]string{
		0: "OTP_PURPOSE_EMAIL_VERIFICATION",
	}
	OtpPurpose_value = map[string]int32{
		"OTP_PURPOSE_EMAIL_VERIFICATION": 0,
	}
)

func (x OtpPurpose) Enum() *OtpPurpose {
	p := new(OtpPurpose)
	*p = x
	return p
}

func (x OtpPurpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OtpPurpose) Descriptor() protoreflect.EnumDescriptor {
	return file_auth_v1_challenge_proto_enumTypes[1].Descriptor()
}

func (OtpPurpose) Type() protoreflect.EnumType {
	return &file_auth_v1_challenge_proto_enumTypes[1]
}

func (x OtpPurpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OtpPurpose.Descriptor instead.
func (OtpPurpose) EnumDescriptor() ([]byte, []int) {
	return file_auth_v1_challenge_proto_rawDescGZIP(), []int{1}
}

type CreateChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Destination   string                 `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	Channel       OtpChannel             `protobuf:"varint,2,opt,name=channel,proto3,enum=api.auth.v1.OtpChannel" json:"channel,omitempty"`
	Purpose       OtpPurpose             `protobuf:"varint,3,opt,name=purpose,proto3,enum=api.auth.v1.OtpPurpose" json:"purpose,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChallengeRequest) Reset() {
	*x = CreateChallengeRequest{}
	mi := &file_auth_v1_challenge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChallengeRequest) ProtoMessage() {}

func (x *CreateChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_challenge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChallengeRequest.ProtoReflect.Descriptor instead.
func (*CreateChallengeRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_challenge_proto_rawDescGZIP(), []int{0}
}

func (x *CreateChallengeRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *CreateChallengeRequest) GetChannel() OtpChannel {
	if x != nil {
		return x.Channel
	}
	return OtpChannel_OTP_CHANNEL_EMAIL
}

func (x *CreateChallengeRequest) GetPurpose() OtpPurpose {
	if x != nil {
		return x.Purpose
	}
	return OtpPurpose_OTP_PURPOSE_EMAIL_VERIFICATION
}

type CreateChallengeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChallengeResponse) Reset() {
	*x = CreateChallengeResponse{}
	mi := &file_auth_v1_challenge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChallengeResponse) ProtoMessage() {}

func (x *CreateChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_challenge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChallengeResponse.ProtoReflect.Descriptor instead.
func (*CreateChallengeResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_challenge_proto_rawDescGZIP(), []int{1}
}

func (x *CreateChallengeResponse) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

type VerifyChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Purpose       OtpPurpose             `protobuf:"varint,2,opt,name=purpose,proto3,enum=api.auth.v1.OtpPurpose" json:"purpose,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyChallengeRequest) Reset() {
	*x = VerifyChallengeRequest{}
	mi := &file_auth_v1_challenge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyChallengeRequest) ProtoMessage() {}

func (x *VerifyChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_challenge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyChallengeRequest.ProtoReflect.Descriptor instead.
func (*VerifyChallengeRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_challenge_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyChallengeRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *VerifyChallengeRequest) GetPurpose() OtpPurpose {
	if x != nil {
		return x.Purpose
	}
	return OtpPurpose_OTP_PURPOSE_EMAIL_VERIFICATION
}

func (x *VerifyChallengeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type VerifyChallengeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verified      bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyChallengeResponse) Reset() {
	*x = VerifyChallengeResponse{}
	mi := &file_auth_v1_challenge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyChallengeResponse) ProtoMessage() {}

func (x *VerifyChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_challenge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyChallengeResponse.ProtoReflect.Descriptor instead.
func (*VerifyChallengeResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_challenge_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyChallengeResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

var File_auth_v1_challenge_proto protoreflect.FileDescriptor

const file_auth_v1_challenge_proto_rawDesc = "" +
	"\n" +
	"\x17auth/v1/challenge.proto\x12\vapi.auth.v1\"\xa0\x01\n" +
	"\x16CreateChallengeRequest\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination\x121\n" +
	"\achannel\x18\x02 \x01(\x0e2\x17.api.auth.v1.OtpChannelR\achannel\x121\n" +
	"\apurpose\x18\x03 \x01(\x0e2\x17.api.auth.v1.OtpPurposeR\apurpose\"<\n" +
	"\x17CreateChallengeResponse\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\"\x82\x01\n" +
	"\x16VerifyChallengeRequest\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x121\n" +
	"\apurpose\x18\x02 \x01(\x0e2\x17.api.auth.v1.OtpPurposeR\apurpose\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"5\n" +
	"\x17VerifyChallengeResponse\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified*8\n" +
	"\n" +
	"OtpChannel\x12\x15\n" +
	"\x11OTP_CHANNEL_EMAIL\x10\x00\x12\x13\n" +
	"\x0fOTP_CHANNEL_SMS\x10\x01*0\n" +
	"\n" +
	"OtpPurpose\x12\"\n" +
	"\x1eOTP_PURPOSE_EMAIL_VERIFICATION\x10\x002\xc8\x01\n" +
	"\n" +
	"OtpService\x12\\\n" +
	"\x0fCreateChallenge\x12#.api.auth.v1.CreateChallengeRequest\x1a$.api.auth.v1.CreateChallengeResponse\x12\\\n" +
	"\x0fVerifyChallenge\x12#.api.auth.v1.VerifyChallengeRequest\x1a$.api.auth.v1.VerifyChallengeResponseB?Z=github.com/mikhaeris/sky-bank/auth_service/api/auth/v1;authv1b\x06proto3"

var (
	file_auth_v1_challenge_proto_rawDescOnce sync.Once
	file_auth_v1_challenge_proto_rawDescData []byte
)

func file_auth_v1_challenge_proto_rawDescGZIP() []byte {
	file_auth_v1_challenge_proto_rawDescOnce.Do(func() {
		file_auth_v1_challenge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_challenge_proto_rawDesc), len(file_auth_v1_challenge_proto_rawDesc)))
	})
	return file_auth_v1_challenge_proto_rawDescData
}

var file_auth_v1_challenge_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_auth_v1_challenge_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_auth_v1_challenge_proto_goTypes = []any{
	(OtpChannel)(0),                 // 0: api.auth.v1.OtpChannel
	(OtpPurpose)(0),                 // 1: api.auth.v1.OtpPurpose
	(*CreateChallengeRequest)(nil),  // 2: api.auth.v1.CreateChallengeRequest
	(*CreateChallengeResponse)(nil), // 3: api.auth.v1.CreateChallengeResponse
	(*VerifyChallengeRequest)(nil),  // 4: api.auth.v1.VerifyChallengeRequest
	(*VerifyChallengeResponse)(nil), // 5: api.auth.v1.VerifyChallengeResponse
}
var file_auth_v1_challenge_proto_depIdxs = []int32{
	0, // 0: api.auth.v1.CreateChallengeRequest.channel:type_name -> api.auth.v1.OtpChannel
	1, // 1: api.auth.v1.CreateChallengeRequest.purpose:type_name -> api.auth.v1.OtpPurpose
	1, // 2: api.auth.v1.VerifyChallengeRequest.purpose:type_name -> api.auth.v1.OtpPurpose
	2, // 3: api.auth.v1.OtpService.CreateChallenge:input_type -> api.auth.v1.CreateChallengeRequest
	4, // 4: api.auth.v1.OtpService.VerifyChallenge:input_type -> api.auth.v1.VerifyChallengeRequest
	3, // 5: api.auth.v1.OtpService.CreateChallenge:output_type -> api.auth.v1.CreateChallengeResponse
	5, // 6: api.auth.v1.OtpService.VerifyChallenge:output_type -> api.auth.v1.VerifyChallengeResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_auth_v1_challenge_proto_init() }
func file_auth_v1_challenge_proto_init() {
	if File_auth_v1_challenge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_challenge_proto_rawDesc), len(file_auth_v1_challenge_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_challenge_proto_goTypes,
		DependencyIndexes: file_auth_v1_challenge_proto_depIdxs,
		EnumInfos:         file_auth_v1_challenge_proto_enumTypes,
		MessageInfos:      file_auth_v1_challenge_proto_msgTypes,
	}.Build()
	File_auth_v1_challenge_proto = out.File
	file_auth_v1_challenge_proto_goTypes = nil
	file_auth_v1_challenge_proto_depIdxs = nil
}
