server:
  grpc:
    addr: 0.0.0.0:9000

database:
  host: postgres
  port: 5432
  database: skybankDB
  username: mikhaeris
  password: qwerty

jwt:
  priv_key_path: /keys/private.pem
  access_token_ttl: 15m
