// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: notification/v1/notification.proto

package notificationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WelcomeMessageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IdentityUuid    string                 `protobuf:"bytes,1,opt,name=identity_uuid,json=identityUuid,proto3" json:"identity_uuid,omitempty"`
	Email           string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	ActivationToken string                 `protobuf:"bytes,3,opt,name=activation_token,json=activationToken,proto3" json:"activation_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WelcomeMessageRequest) Reset() {
	*x = WelcomeMessageRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomeMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeMessageRequest) ProtoMessage() {}

func (x *WelcomeMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeMessageRequest.ProtoReflect.Descriptor instead.
func (*WelcomeMessageRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *WelcomeMessageRequest) GetIdentityUuid() string {
	if x != nil {
		return x.IdentityUuid
	}
	return ""
}

func (x *WelcomeMessageRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *WelcomeMessageRequest) GetActivationToken() string {
	if x != nil {
		return x.ActivationToken
	}
	return ""
}

type WelcomeMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WelcomeMessageResponse) Reset() {
	*x = WelcomeMessageResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomeMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeMessageResponse) ProtoMessage() {}

func (x *WelcomeMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeMessageResponse.ProtoReflect.Descriptor instead.
func (*WelcomeMessageResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *WelcomeMessageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type WelcomeActivatedMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WelcomeActivatedMessageRequest) Reset() {
	*x = WelcomeActivatedMessageRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomeActivatedMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeActivatedMessageRequest) ProtoMessage() {}

func (x *WelcomeActivatedMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeActivatedMessageRequest.ProtoReflect.Descriptor instead.
func (*WelcomeActivatedMessageRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{2}
}

func (x *WelcomeActivatedMessageRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type WelcomeActivatedMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WelcomeActivatedMessageResponse) Reset() {
	*x = WelcomeActivatedMessageResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomeActivatedMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeActivatedMessageResponse) ProtoMessage() {}

func (x *WelcomeActivatedMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeActivatedMessageResponse.ProtoReflect.Descriptor instead.
func (*WelcomeActivatedMessageResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{3}
}

func (x *WelcomeActivatedMessageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ResetPasswordMessageRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IdentityUuid       string                 `protobuf:"bytes,1,opt,name=identity_uuid,json=identityUuid,proto3" json:"identity_uuid,omitempty"`
	Email              string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	ResetPasswordToken string                 `protobuf:"bytes,3,opt,name=reset_password_token,json=resetPasswordToken,proto3" json:"reset_password_token,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResetPasswordMessageRequest) Reset() {
	*x = ResetPasswordMessageRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordMessageRequest) ProtoMessage() {}

func (x *ResetPasswordMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordMessageRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordMessageRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{4}
}

func (x *ResetPasswordMessageRequest) GetIdentityUuid() string {
	if x != nil {
		return x.IdentityUuid
	}
	return ""
}

func (x *ResetPasswordMessageRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResetPasswordMessageRequest) GetResetPasswordToken() string {
	if x != nil {
		return x.ResetPasswordToken
	}
	return ""
}

type ResetPasswordMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordMessageResponse) Reset() {
	*x = ResetPasswordMessageResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordMessageResponse) ProtoMessage() {}

func (x *ResetPasswordMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordMessageResponse.ProtoReflect.Descriptor instead.
func (*ResetPasswordMessageResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{5}
}

func (x *ResetPasswordMessageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RecoveryMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityUuid  string                 `protobuf:"bytes,1,opt,name=identity_uuid,json=identityUuid,proto3" json:"identity_uuid,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	SecurityToken string                 `protobuf:"bytes,3,opt,name=security_token,json=securityToken,proto3" json:"security_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoveryMessageRequest) Reset() {
	*x = RecoveryMessageRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryMessageRequest) ProtoMessage() {}

func (x *RecoveryMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryMessageRequest.ProtoReflect.Descriptor instead.
func (*RecoveryMessageRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{6}
}

func (x *RecoveryMessageRequest) GetIdentityUuid() string {
	if x != nil {
		return x.IdentityUuid
	}
	return ""
}

func (x *RecoveryMessageRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RecoveryMessageRequest) GetSecurityToken() string {
	if x != nil {
		return x.SecurityToken
	}
	return ""
}

type RecoveryMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoveryMessageResponse) Reset() {
	*x = RecoveryMessageResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoveryMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoveryMessageResponse) ProtoMessage() {}

func (x *RecoveryMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoveryMessageResponse.ProtoReflect.Descriptor instead.
func (*RecoveryMessageResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{7}
}

func (x *RecoveryMessageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_notification_v1_notification_proto protoreflect.FileDescriptor

const file_notification_v1_notification_proto_rawDesc = "" +
	"\n" +
	"\"notification/v1/notification.proto\x12\x13api.notification.v1\"}\n" +
	"\x15WelcomeMessageRequest\x12#\n" +
	"\ridentity_uuid\x18\x01 \x01(\tR\fidentityUuid\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12)\n" +
	"\x10activation_token\x18\x03 \x01(\tR\x0factivationToken\"0\n" +
	"\x16WelcomeMessageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"6\n" +
	"\x1eWelcomeActivatedMessageRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"9\n" +
	"\x1fWelcomeActivatedMessageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x8a\x01\n" +
	"\x1bResetPasswordMessageRequest\x12#\n" +
	"\ridentity_uuid\x18\x01 \x01(\tR\fidentityUuid\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x120\n" +
	"\x14reset_password_token\x18\x03 \x01(\tR\x12resetPasswordToken\"6\n" +
	"\x1cResetPasswordMessageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"z\n" +
	"\x16RecoveryMessageRequest\x12#\n" +
	"\ridentity_uuid\x18\x01 \x01(\tR\fidentityUuid\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12%\n" +
	"\x0esecurity_token\x18\x03 \x01(\tR\rsecurityToken\"1\n" +
	"\x17RecoveryMessageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x82\x04\n" +
	"\x13NotificationService\x12m\n" +
	"\x12SendWelcomeMessage\x12*.api.notification.v1.WelcomeMessageRequest\x1a+.api.notification.v1.WelcomeMessageResponse\x12\x88\x01\n" +
	"\x1bSendWelcomeActivatedMessage\x123.api.notification.v1.WelcomeActivatedMessageRequest\x1a4.api.notification.v1.WelcomeActivatedMessageResponse\x12\x7f\n" +
	"\x18SendResetPasswordMessage\x120.api.notification.v1.ResetPasswordMessageRequest\x1a1.api.notification.v1.ResetPasswordMessageResponse\x12p\n" +
	"\x13SendRecoveryMessage\x12+.api.notification.v1.RecoveryMessageRequest\x1a,.api.notification.v1.RecoveryMessageResponseBWZUgithub.com/mikhaeris/sky-bank/notification_service/api/notification/v1;notificationv1b\x06proto3"

var (
	file_notification_v1_notification_proto_rawDescOnce sync.Once
	file_notification_v1_notification_proto_rawDescData []byte
)

func file_notification_v1_notification_proto_rawDescGZIP() []byte {
	file_notification_v1_notification_proto_rawDescOnce.Do(func() {
		file_notification_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_v1_notification_proto_rawDesc), len(file_notification_v1_notification_proto_rawDesc)))
	})
	return file_notification_v1_notification_proto_rawDescData
}

var file_notification_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_notification_v1_notification_proto_goTypes = []any{
	(*WelcomeMessageRequest)(nil),           // 0: api.notification.v1.WelcomeMessageRequest
	(*WelcomeMessageResponse)(nil),          // 1: api.notification.v1.WelcomeMessageResponse
	(*WelcomeActivatedMessageRequest)(nil),  // 2: api.notification.v1.WelcomeActivatedMessageRequest
	(*WelcomeActivatedMessageResponse)(nil), // 3: api.notification.v1.WelcomeActivatedMessageResponse
	(*ResetPasswordMessageRequest)(nil),     // 4: api.notification.v1.ResetPasswordMessageRequest
	(*ResetPasswordMessageResponse)(nil),    // 5: api.notification.v1.ResetPasswordMessageResponse
	(*RecoveryMessageRequest)(nil),          // 6: api.notification.v1.RecoveryMessageRequest
	(*RecoveryMessageResponse)(nil),         // 7: api.notification.v1.RecoveryMessageResponse
}
var file_notification_v1_notification_proto_depIdxs = []int32{
	0, // 0: api.notification.v1.NotificationService.SendWelcomeMessage:input_type -> api.notification.v1.WelcomeMessageRequest
	2, // 1: api.notification.v1.NotificationService.SendWelcomeActivatedMessage:input_type -> api.notification.v1.WelcomeActivatedMessageRequest
	4, // 2: api.notification.v1.NotificationService.SendResetPasswordMessage:input_type -> api.notification.v1.ResetPasswordMessageRequest
	6, // 3: api.notification.v1.NotificationService.SendRecoveryMessage:input_type -> api.notification.v1.RecoveryMessageRequest
	1, // 4: api.notification.v1.NotificationService.SendWelcomeMessage:output_type -> api.notification.v1.WelcomeMessageResponse
	3, // 5: api.notification.v1.NotificationService.SendWelcomeActivatedMessage:output_type -> api.notification.v1.WelcomeActivatedMessageResponse
	5, // 6: api.notification.v1.NotificationService.SendResetPasswordMessage:output_type -> api.notification.v1.ResetPasswordMessageResponse
	7, // 7: api.notification.v1.NotificationService.SendRecoveryMessage:output_type -> api.notification.v1.RecoveryMessageResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notification_v1_notification_proto_init() }
func file_notification_v1_notification_proto_init() {
	if File_notification_v1_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_v1_notification_proto_rawDesc), len(file_notification_v1_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_v1_notification_proto_goTypes,
		DependencyIndexes: file_notification_v1_notification_proto_depIdxs,
		MessageInfos:      file_notification_v1_notification_proto_msgTypes,
	}.Build()
	File_notification_v1_notification_proto = out.File
	file_notification_v1_notification_proto_goTypes = nil
	file_notification_v1_notification_proto_depIdxs = nil
}
