// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: notification/v1/notification.proto

package notificationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WelcomeMessageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IdentityUuid    string                 `protobuf:"bytes,1,opt,name=identity_uuid,json=identityUuid,proto3" json:"identity_uuid,omitempty"`
	Email           string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	ActivationToken string                 `protobuf:"bytes,3,opt,name=activation_token,json=activationToken,proto3" json:"activation_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WelcomeMessageRequest) Reset() {
	*x = WelcomeMessageRequest{}
	mi := &file_notification_v1_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomeMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeMessageRequest) ProtoMessage() {}

func (x *WelcomeMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeMessageRequest.ProtoReflect.Descriptor instead.
func (*WelcomeMessageRequest) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{0}
}

func (x *WelcomeMessageRequest) GetIdentityUuid() string {
	if x != nil {
		return x.IdentityUuid
	}
	return ""
}

func (x *WelcomeMessageRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *WelcomeMessageRequest) GetActivationToken() string {
	if x != nil {
		return x.ActivationToken
	}
	return ""
}

type WelcomeMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WelcomeMessageResponse) Reset() {
	*x = WelcomeMessageResponse{}
	mi := &file_notification_v1_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WelcomeMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WelcomeMessageResponse) ProtoMessage() {}

func (x *WelcomeMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_v1_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WelcomeMessageResponse.ProtoReflect.Descriptor instead.
func (*WelcomeMessageResponse) Descriptor() ([]byte, []int) {
	return file_notification_v1_notification_proto_rawDescGZIP(), []int{1}
}

func (x *WelcomeMessageResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_notification_v1_notification_proto protoreflect.FileDescriptor

const file_notification_v1_notification_proto_rawDesc = "" +
	"\n" +
	"\"notification/v1/notification.proto\x12\x13api.notification.v1\"}\n" +
	"\x15WelcomeMessageRequest\x12#\n" +
	"\ridentity_uuid\x18\x01 \x01(\tR\fidentityUuid\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12)\n" +
	"\x10activation_token\x18\x03 \x01(\tR\x0factivationToken\"0\n" +
	"\x16WelcomeMessageResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x84\x01\n" +
	"\x13NotificationService\x12m\n" +
	"\x12SendWelcomeMessage\x12*.api.notification.v1.WelcomeMessageRequest\x1a+.api.notification.v1.WelcomeMessageResponseBWZUgithub.com/mikhaeris/sky-bank/notification_service/api/notification/v1;notificationv1b\x06proto3"

var (
	file_notification_v1_notification_proto_rawDescOnce sync.Once
	file_notification_v1_notification_proto_rawDescData []byte
)

func file_notification_v1_notification_proto_rawDescGZIP() []byte {
	file_notification_v1_notification_proto_rawDescOnce.Do(func() {
		file_notification_v1_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_v1_notification_proto_rawDesc), len(file_notification_v1_notification_proto_rawDesc)))
	})
	return file_notification_v1_notification_proto_rawDescData
}

var file_notification_v1_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notification_v1_notification_proto_goTypes = []any{
	(*WelcomeMessageRequest)(nil),  // 0: api.notification.v1.WelcomeMessageRequest
	(*WelcomeMessageResponse)(nil), // 1: api.notification.v1.WelcomeMessageResponse
}
var file_notification_v1_notification_proto_depIdxs = []int32{
	0, // 0: api.notification.v1.NotificationService.SendWelcomeMessage:input_type -> api.notification.v1.WelcomeMessageRequest
	1, // 1: api.notification.v1.NotificationService.SendWelcomeMessage:output_type -> api.notification.v1.WelcomeMessageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notification_v1_notification_proto_init() }
func file_notification_v1_notification_proto_init() {
	if File_notification_v1_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_v1_notification_proto_rawDesc), len(file_notification_v1_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_v1_notification_proto_goTypes,
		DependencyIndexes: file_notification_v1_notification_proto_depIdxs,
		MessageInfos:      file_notification_v1_notification_proto_msgTypes,
	}.Build()
	File_notification_v1_notification_proto = out.File
	file_notification_v1_notification_proto_goTypes = nil
	file_notification_v1_notification_proto_depIdxs = nil
}
