syntax = "proto3";

package api.notification.v1;

option go_package = "github.com/mikhaeris/sky-bank/notification_service/api/notification/v1;notificationv1";

service NotificationService {
    rpc SendWelcomeMessage(WelcomeMessageRequest) returns (WelcomeMessageResponse);
    rpc SendWelcomeActivatedMessage(WelcomeActivatedMessageRequest) returns (WelcomeActivatedMessageResponse);
    rpc SendResetPasswordMessage(ResetPasswordMessageRequest) returns (ResetPasswordMessageResponse);
    rpc SendRecoveryMessage(RecoveryMessageRequest) returns (RecoveryMessageResponse);
}

message WelcomeMessageRequest {
    string identity_uuid = 1;
    string email = 2;
    string activation_token = 3;
}

message WelcomeMessageResponse {
    string status = 1;
}

message WelcomeActivatedMessageRequest {
    string email = 1;
}

message WelcomeActivatedMessageResponse {
    string status = 1;
}

message ResetPasswordMessageRequest {
    string identity_uuid = 1;
    string email = 2;
    string reset_password_token = 3;
}

message ResetPasswordMessageResponse {
    string status = 1;
}

message RecoveryMessageRequest {
    string identity_uuid = 1;
    string email = 2;
    string security_token = 3;
}

message RecoveryMessageResponse {
    string status = 1;
}
