// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: customer/v1/customer_private.proto

package customerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateEmptyCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmptyCustomerRequest) Reset() {
	*x = CreateEmptyCustomerRequest{}
	mi := &file_customer_v1_customer_private_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmptyCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmptyCustomerRequest) ProtoMessage() {}

func (x *CreateEmptyCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_v1_customer_private_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmptyCustomerRequest.ProtoReflect.Descriptor instead.
func (*CreateEmptyCustomerRequest) Descriptor() ([]byte, []int) {
	return file_customer_v1_customer_private_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEmptyCustomerRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

var File_customer_v1_customer_private_proto protoreflect.FileDescriptor

const file_customer_v1_customer_private_proto_rawDesc = "" +
	"\n" +
	"\"customer/v1/customer_private.proto\x12\x0fapi.customer.v1\x1a\x1bgoogle/protobuf/empty.proto\"=\n" +
	"\x1aCreateEmptyCustomerRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId2m\n" +
	"\x0fCustomerPrivate\x12Z\n" +
	"\x13CreateEmptyCustomer\x12+.api.customer.v1.CreateEmptyCustomerRequest\x1a\x16.google.protobuf.EmptyBKZIgithub.com/mikhaeris/sky-bank/customer_service/api/customer/v1;customerv1b\x06proto3"

var (
	file_customer_v1_customer_private_proto_rawDescOnce sync.Once
	file_customer_v1_customer_private_proto_rawDescData []byte
)

func file_customer_v1_customer_private_proto_rawDescGZIP() []byte {
	file_customer_v1_customer_private_proto_rawDescOnce.Do(func() {
		file_customer_v1_customer_private_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_customer_v1_customer_private_proto_rawDesc), len(file_customer_v1_customer_private_proto_rawDesc)))
	})
	return file_customer_v1_customer_private_proto_rawDescData
}

var file_customer_v1_customer_private_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_customer_v1_customer_private_proto_goTypes = []any{
	(*CreateEmptyCustomerRequest)(nil), // 0: api.customer.v1.CreateEmptyCustomerRequest
	(*emptypb.Empty)(nil),              // 1: google.protobuf.Empty
}
var file_customer_v1_customer_private_proto_depIdxs = []int32{
	0, // 0: api.customer.v1.CustomerPrivate.CreateEmptyCustomer:input_type -> api.customer.v1.CreateEmptyCustomerRequest
	1, // 1: api.customer.v1.CustomerPrivate.CreateEmptyCustomer:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_customer_v1_customer_private_proto_init() }
func file_customer_v1_customer_private_proto_init() {
	if File_customer_v1_customer_private_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_customer_v1_customer_private_proto_rawDesc), len(file_customer_v1_customer_private_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_customer_v1_customer_private_proto_goTypes,
		DependencyIndexes: file_customer_v1_customer_private_proto_depIdxs,
		MessageInfos:      file_customer_v1_customer_private_proto_msgTypes,
	}.Build()
	File_customer_v1_customer_private_proto = out.File
	file_customer_v1_customer_private_proto_goTypes = nil
	file_customer_v1_customer_private_proto_depIdxs = nil
}
