// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: customer/v1/customer.proto

package customerv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	MiddleName    string                 `protobuf:"bytes,4,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	BirthDate     string                 `protobuf:"bytes,5,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Gender        string                 `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_customer_v1_customer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_customer_v1_customer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_customer_v1_customer_proto_rawDescGZIP(), []int{0}
}

func (x *Profile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Profile) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Profile) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Profile) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *Profile) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *Profile) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type CompleteProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteProfileRequest) Reset() {
	*x = CompleteProfileRequest{}
	mi := &file_customer_v1_customer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteProfileRequest) ProtoMessage() {}

func (x *CompleteProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_v1_customer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteProfileRequest.ProtoReflect.Descriptor instead.
func (*CompleteProfileRequest) Descriptor() ([]byte, []int) {
	return file_customer_v1_customer_proto_rawDescGZIP(), []int{1}
}

func (x *CompleteProfileRequest) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type CompleteProfileResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Profile          *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	EmailVerified    bool                   `protobuf:"varint,2,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	ProfileCompleted bool                   `protobuf:"varint,3,opt,name=profile_completed,json=profileCompleted,proto3" json:"profile_completed,omitempty"`
	KycStatus        string                 `protobuf:"bytes,4,opt,name=kyc_status,json=kycStatus,proto3" json:"kyc_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CompleteProfileResponse) Reset() {
	*x = CompleteProfileResponse{}
	mi := &file_customer_v1_customer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteProfileResponse) ProtoMessage() {}

func (x *CompleteProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_v1_customer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteProfileResponse.ProtoReflect.Descriptor instead.
func (*CompleteProfileResponse) Descriptor() ([]byte, []int) {
	return file_customer_v1_customer_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteProfileResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *CompleteProfileResponse) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *CompleteProfileResponse) GetProfileCompleted() bool {
	if x != nil {
		return x.ProfileCompleted
	}
	return false
}

func (x *CompleteProfileResponse) GetKycStatus() string {
	if x != nil {
		return x.KycStatus
	}
	return ""
}

type StartEmailVerificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartEmailVerificationRequest) Reset() {
	*x = StartEmailVerificationRequest{}
	mi := &file_customer_v1_customer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartEmailVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEmailVerificationRequest) ProtoMessage() {}

func (x *StartEmailVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_v1_customer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartEmailVerificationRequest.ProtoReflect.Descriptor instead.
func (*StartEmailVerificationRequest) Descriptor() ([]byte, []int) {
	return file_customer_v1_customer_proto_rawDescGZIP(), []int{3}
}

func (x *StartEmailVerificationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type StartEmailVerificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartEmailVerificationResponse) Reset() {
	*x = StartEmailVerificationResponse{}
	mi := &file_customer_v1_customer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartEmailVerificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEmailVerificationResponse) ProtoMessage() {}

func (x *StartEmailVerificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_v1_customer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartEmailVerificationResponse.ProtoReflect.Descriptor instead.
func (*StartEmailVerificationResponse) Descriptor() ([]byte, []int) {
	return file_customer_v1_customer_proto_rawDescGZIP(), []int{4}
}

func (x *StartEmailVerificationResponse) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

type CompleteEmailVerificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId   string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	OtpCode       string                 `protobuf:"bytes,3,opt,name=otp_code,json=otpCode,proto3" json:"otp_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteEmailVerificationRequest) Reset() {
	*x = CompleteEmailVerificationRequest{}
	mi := &file_customer_v1_customer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteEmailVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteEmailVerificationRequest) ProtoMessage() {}

func (x *CompleteEmailVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_v1_customer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteEmailVerificationRequest.ProtoReflect.Descriptor instead.
func (*CompleteEmailVerificationRequest) Descriptor() ([]byte, []int) {
	return file_customer_v1_customer_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteEmailVerificationRequest) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *CompleteEmailVerificationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CompleteEmailVerificationRequest) GetOtpCode() string {
	if x != nil {
		return x.OtpCode
	}
	return ""
}

type GetCustomerResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Profile          *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	EmailVerified    bool                   `protobuf:"varint,2,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	ProfileCompleted bool                   `protobuf:"varint,3,opt,name=profile_completed,json=profileCompleted,proto3" json:"profile_completed,omitempty"`
	KycStatus        string                 `protobuf:"bytes,4,opt,name=kyc_status,json=kycStatus,proto3" json:"kyc_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetCustomerResponse) Reset() {
	*x = GetCustomerResponse{}
	mi := &file_customer_v1_customer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerResponse) ProtoMessage() {}

func (x *GetCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_v1_customer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerResponse) Descriptor() ([]byte, []int) {
	return file_customer_v1_customer_proto_rawDescGZIP(), []int{6}
}

func (x *GetCustomerResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

func (x *GetCustomerResponse) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *GetCustomerResponse) GetProfileCompleted() bool {
	if x != nil {
		return x.ProfileCompleted
	}
	return false
}

func (x *GetCustomerResponse) GetKycStatus() string {
	if x != nil {
		return x.KycStatus
	}
	return ""
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_customer_v1_customer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_v1_customer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_customer_v1_customer_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProfileRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SubmitCustomerKYCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitCustomerKYCRequest) Reset() {
	*x = SubmitCustomerKYCRequest{}
	mi := &file_customer_v1_customer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitCustomerKYCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitCustomerKYCRequest) ProtoMessage() {}

func (x *SubmitCustomerKYCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_v1_customer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitCustomerKYCRequest.ProtoReflect.Descriptor instead.
func (*SubmitCustomerKYCRequest) Descriptor() ([]byte, []int) {
	return file_customer_v1_customer_proto_rawDescGZIP(), []int{8}
}

func (x *SubmitCustomerKYCRequest) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

var File_customer_v1_customer_proto protoreflect.FileDescriptor

const file_customer_v1_customer_proto_rawDesc = "" +
	"\n" +
	"\x1acustomer/v1/customer.proto\x12\x0fapi.customer.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb3\x01\n" +
	"\aProfile\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x1f\n" +
	"\vmiddle_name\x18\x04 \x01(\tR\n" +
	"middleName\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x05 \x01(\tR\tbirthDate\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\"L\n" +
	"\x16CompleteProfileRequest\x122\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.api.customer.v1.ProfileR\aprofile\"\xc0\x01\n" +
	"\x17CompleteProfileResponse\x122\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.api.customer.v1.ProfileR\aprofile\x12%\n" +
	"\x0eemail_verified\x18\x02 \x01(\bR\remailVerified\x12+\n" +
	"\x11profile_completed\x18\x03 \x01(\bR\x10profileCompleted\x12\x1d\n" +
	"\n" +
	"kyc_status\x18\x04 \x01(\tR\tkycStatus\"5\n" +
	"\x1dStartEmailVerificationRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"C\n" +
	"\x1eStartEmailVerificationResponse\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\"v\n" +
	" CompleteEmailVerificationRequest\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x19\n" +
	"\botp_code\x18\x03 \x01(\tR\aotpCode\"\xbc\x01\n" +
	"\x13GetCustomerResponse\x122\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.api.customer.v1.ProfileR\aprofile\x12%\n" +
	"\x0eemail_verified\x18\x02 \x01(\bR\remailVerified\x12+\n" +
	"\x11profile_completed\x18\x03 \x01(\bR\x10profileCompleted\x12\x1d\n" +
	"\n" +
	"kyc_status\x18\x04 \x01(\tR\tkycStatus\",\n" +
	"\x14UpdateProfileRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"N\n" +
	"\x18SubmitCustomerKYCRequest\x122\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.api.customer.v1.ProfileR\aprofile2\x8b\x06\n" +
	"\bCustomer\x12z\n" +
	"\x0fCompleteProfile\x12'.api.customer.v1.CompleteProfileRequest\x1a(.api.customer.v1.CompleteProfileResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/customer\x12\xa8\x01\n" +
	"\x16StartEmailVerification\x12..api.customer.v1.StartEmailVerificationRequest\x1a/.api.customer.v1.StartEmailVerificationResponse\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/customer/email-verification/start\x12\x98\x01\n" +
	"\x19CompleteEmailVerification\x121.api.customer.v1.CompleteEmailVerificationRequest\x1a\x16.google.protobuf.Empty\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/customer/email-verification/complete\x12^\n" +
	"\vGetCustomer\x12\x16.google.protobuf.Empty\x1a$.api.customer.v1.GetCustomerResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/customer\x12d\n" +
	"\rUpdateProfile\x12%.api.customer.v1.UpdateProfileRequest\x1a\x16.google.protobuf.Empty\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*2\t/customer\x12w\n" +
	"\x11SubmitCustomerKYC\x12).api.customer.v1.SubmitCustomerKYCRequest\x1a\x16.google.protobuf.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/customer/kyc/submitBKZIgithub.com/mikhaeris/sky-bank/customer_service/api/customer/v1;customerv1b\x06proto3"

var (
	file_customer_v1_customer_proto_rawDescOnce sync.Once
	file_customer_v1_customer_proto_rawDescData []byte
)

func file_customer_v1_customer_proto_rawDescGZIP() []byte {
	file_customer_v1_customer_proto_rawDescOnce.Do(func() {
		file_customer_v1_customer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_customer_v1_customer_proto_rawDesc), len(file_customer_v1_customer_proto_rawDesc)))
	})
	return file_customer_v1_customer_proto_rawDescData
}

var file_customer_v1_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_customer_v1_customer_proto_goTypes = []any{
	(*Profile)(nil),                          // 0: api.customer.v1.Profile
	(*CompleteProfileRequest)(nil),           // 1: api.customer.v1.CompleteProfileRequest
	(*CompleteProfileResponse)(nil),          // 2: api.customer.v1.CompleteProfileResponse
	(*StartEmailVerificationRequest)(nil),    // 3: api.customer.v1.StartEmailVerificationRequest
	(*StartEmailVerificationResponse)(nil),   // 4: api.customer.v1.StartEmailVerificationResponse
	(*CompleteEmailVerificationRequest)(nil), // 5: api.customer.v1.CompleteEmailVerificationRequest
	(*GetCustomerResponse)(nil),              // 6: api.customer.v1.GetCustomerResponse
	(*UpdateProfileRequest)(nil),             // 7: api.customer.v1.UpdateProfileRequest
	(*SubmitCustomerKYCRequest)(nil),         // 8: api.customer.v1.SubmitCustomerKYCRequest
	(*emptypb.Empty)(nil),                    // 9: google.protobuf.Empty
}
var file_customer_v1_customer_proto_depIdxs = []int32{
	0,  // 0: api.customer.v1.CompleteProfileRequest.profile:type_name -> api.customer.v1.Profile
	0,  // 1: api.customer.v1.CompleteProfileResponse.profile:type_name -> api.customer.v1.Profile
	0,  // 2: api.customer.v1.GetCustomerResponse.profile:type_name -> api.customer.v1.Profile
	0,  // 3: api.customer.v1.SubmitCustomerKYCRequest.profile:type_name -> api.customer.v1.Profile
	1,  // 4: api.customer.v1.Customer.CompleteProfile:input_type -> api.customer.v1.CompleteProfileRequest
	3,  // 5: api.customer.v1.Customer.StartEmailVerification:input_type -> api.customer.v1.StartEmailVerificationRequest
	5,  // 6: api.customer.v1.Customer.CompleteEmailVerification:input_type -> api.customer.v1.CompleteEmailVerificationRequest
	9,  // 7: api.customer.v1.Customer.GetCustomer:input_type -> google.protobuf.Empty
	7,  // 8: api.customer.v1.Customer.UpdateProfile:input_type -> api.customer.v1.UpdateProfileRequest
	8,  // 9: api.customer.v1.Customer.SubmitCustomerKYC:input_type -> api.customer.v1.SubmitCustomerKYCRequest
	2,  // 10: api.customer.v1.Customer.CompleteProfile:output_type -> api.customer.v1.CompleteProfileResponse
	4,  // 11: api.customer.v1.Customer.StartEmailVerification:output_type -> api.customer.v1.StartEmailVerificationResponse
	9,  // 12: api.customer.v1.Customer.CompleteEmailVerification:output_type -> google.protobuf.Empty
	6,  // 13: api.customer.v1.Customer.GetCustomer:output_type -> api.customer.v1.GetCustomerResponse
	9,  // 14: api.customer.v1.Customer.UpdateProfile:output_type -> google.protobuf.Empty
	9,  // 15: api.customer.v1.Customer.SubmitCustomerKYC:output_type -> google.protobuf.Empty
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_customer_v1_customer_proto_init() }
func file_customer_v1_customer_proto_init() {
	if File_customer_v1_customer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_customer_v1_customer_proto_rawDesc), len(file_customer_v1_customer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_customer_v1_customer_proto_goTypes,
		DependencyIndexes: file_customer_v1_customer_proto_depIdxs,
		MessageInfos:      file_customer_v1_customer_proto_msgTypes,
	}.Build()
	File_customer_v1_customer_proto = out.File
	file_customer_v1_customer_proto_goTypes = nil
	file_customer_v1_customer_proto_depIdxs = nil
}
