// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: customer/v1/customer_private.proto

package customerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CustomerPrivate_CreateEmptyCustomer_FullMethodName = "/api.customer.v1.CustomerPrivate/CreateEmptyCustomer"
)

// CustomerPrivateClient is the client API for CustomerPrivate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomerPrivateClient interface {
	CreateEmptyCustomer(ctx context.Context, in *CreateEmptyCustomerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type customerPrivateClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomerPrivateClient(cc grpc.ClientConnInterface) CustomerPrivateClient {
	return &customerPrivateClient{cc}
}

func (c *customerPrivateClient) CreateEmptyCustomer(ctx context.Context, in *CreateEmptyCustomerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CustomerPrivate_CreateEmptyCustomer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerPrivateServer is the server API for CustomerPrivate service.
// All implementations must embed UnimplementedCustomerPrivateServer
// for forward compatibility.
type CustomerPrivateServer interface {
	CreateEmptyCustomer(context.Context, *CreateEmptyCustomerRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedCustomerPrivateServer()
}

// UnimplementedCustomerPrivateServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCustomerPrivateServer struct{}

func (UnimplementedCustomerPrivateServer) CreateEmptyCustomer(context.Context, *CreateEmptyCustomerRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEmptyCustomer not implemented")
}
func (UnimplementedCustomerPrivateServer) mustEmbedUnimplementedCustomerPrivateServer() {}
func (UnimplementedCustomerPrivateServer) testEmbeddedByValue()                         {}

// UnsafeCustomerPrivateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomerPrivateServer will
// result in compilation errors.
type UnsafeCustomerPrivateServer interface {
	mustEmbedUnimplementedCustomerPrivateServer()
}

func RegisterCustomerPrivateServer(s grpc.ServiceRegistrar, srv CustomerPrivateServer) {
	// If the following call panics, it indicates UnimplementedCustomerPrivateServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CustomerPrivate_ServiceDesc, srv)
}

func _CustomerPrivate_CreateEmptyCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEmptyCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerPrivateServer).CreateEmptyCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomerPrivate_CreateEmptyCustomer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerPrivateServer).CreateEmptyCustomer(ctx, req.(*CreateEmptyCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomerPrivate_ServiceDesc is the grpc.ServiceDesc for CustomerPrivate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomerPrivate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.customer.v1.CustomerPrivate",
	HandlerType: (*CustomerPrivateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEmptyCustomer",
			Handler:    _CustomerPrivate_CreateEmptyCustomer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer/v1/customer_private.proto",
}
